# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepadapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=256)),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=1024)),
                ('contact', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=256)),
                ('semester', models.CharField(max_length=256)),
            ],
        ),
    ]
