# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepadapp', '0003_students_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labname', models.CharField(max_length=256)),
                ('semester', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=256)),
            ],
        ),
    ]
