# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codepadapp', '0007_lab_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='Faculty',
            new_name='faculty',
        ),
        migrations.AddField(
            model_name='faculty',
            name='loginid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='codepadapp.Login'),
            preserve_default=False,
        ),
    ]
