# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepadapp', '0008_auto_20160116_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='phone',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
