# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codepadapp', '0009_auto_20160117_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=256)),
                ('programname', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('path', models.CharField(max_length=256)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codepadapp.Lab')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codepadapp.Login')),
            ],
        ),
    ]
