# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codepadapp', '0011_exam_examquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('datetime', models.CharField(max_length=256)),
                ('examquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codepadapp.ExamQuestions')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codepadapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='ExamLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=256)),
            ],
        ),
    ]
