# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepadapp', '0012_examanswers_examlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswers',
            name='name',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
