# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepadapp', '0013_examanswers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswers',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
