# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codepadapp', '0014_auto_20160215_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('total', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('examid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codepadapp.Exam')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codepadapp.Login')),
            ],
        ),
    ]
