# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepadapp', '0015_exammarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.CharField(default='2', max_length=256),
            preserve_default=False,
        ),
    ]
